In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/movies_metadata.csv')
df.head()

/home/scrybe/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [2]:
m = df['vote_count'].quantile(0.80)
m

50.0

In [3]:
df['vote_count'].max()

14075.0

In [4]:
q_movies = df[(df['runtime']>=45)&(df['runtime']<=300)]
q_movies=q_movies[q_movies['vote_count']>=m]
q_movies.shape

(8963, 24)

In [5]:
c=df['vote_average'].mean()
c

5.618207215134185

In [6]:
def weighted_rating(x,m=m,c=c):
    v = x['vote_count']
    R = x['vote_average']
    
    return(v*R + m*c)/(v+m)

In [7]:
q_movies['score'] = q_movies.apply(weighted_rating,axis=1)
q_movies['score']

0        7.680953
1        6.873979
2        6.189510
4        5.681661
5        7.646235
6        6.047698
8        5.526386
9        6.560539
10       6.322933
11       5.684271
12       6.943362
13       6.492708
14       5.678130
15       7.721687
16       7.008962
17       6.425145
18       6.079550
19       5.439819
20       6.289888
21       6.322933
22       5.957005
23       6.123370
24       6.921471
26       6.251847
28       7.323213
30       6.269265
31       7.364647
33       5.976316
35       7.089776
37       5.978947
           ...
44925    5.800073
44939    5.331343
44947    7.142833
44949    7.626404
44951    6.721413
44956    5.518074
44960    7.072736
45014    5.694458
45025    5.868369
45031    5.882886
45036    5.969130
45041    5.455984
45064    5.447318
45139    5.775890
45149    5.608201
45167    7.014331
45174    6.728637
45177    4.613859
45202    5.389889
45204    6.932755
45206    6.581285
45225    6.459104
45239    5.961560
45258    7.074255
45265    6.606263
45268    5.378376
45339    5.345211
45343    4.372859
45348    4.456289
45441    5.307233
Name: score, Length: 8963, dtype: float64

In [9]:
result=q_movies.sort_values(['score'], ascending=False)

In [18]:
result[['original_title','score','vote_count']].head(250)

                                      original_title     score  vote_count
10309                    Dilwale Dulhania Le Jayenge  8.855148       661.0
314                         The Shawshank Redemption  8.482863      8358.0
834                                    The Godfather  8.476278      6024.0
40251                                          君の名は。  8.366584      1030.0
12481                                The Dark Knight  8.289115     12269.0
2843                                      Fight Club  8.286216      9678.0
292                                     Pulp Fiction  8.284623      8670.0
522                                 Schindler's List  8.270109      4436.0
23673                                       Whiplash  8.269704      4376.0
5481                                        千と千尋の神隠し  8.266628      3968.0
2211                                 La vita è bella  8.263691      3643.0
1178                          The Godfather: Part II  8.261335      3418.0
1152                 One Flew Over the Cuckoo's Nest  8.256051      3001.0
1176                                          Psycho  8.245381      2405.0
351                                     Forrest Gump  8.184252      8147.0
1184                     Once Upon a Time in America  8.183804      1104.0
1154                         The Empire Strikes Back  8.178656      5998.0
18465                                   Intouchables  8.176357      5410.0
289                                             Léon  8.170276      4293.0
3030                                  The Green Mile  8.169381      4166.0
1170                                      GoodFellas  8.160414      3211.0
2216                              American History X  8.159278      3120.0
1161                                    12 Angry Men  8.140785      2130.0
9698                                         ハウルの動く城  8.138499      2049.0
2884                                           もののけ姫  8.138264      2041.0
5878                                  Cidade de Deus  8.132130      1852.0
877                                      Rear Window  8.118349      1531.0
15480                                      Inception  8.091215     14075.0
22879                                   Interstellar  8.088957     11187.0
7000   The Lord of the Rings: The Return of the King  8.085006      8226.0
...                                              ...       ...         ...
6861                         The Night of the Hunter  7.603663       335.0
889                                    Roman Holiday  7.602374       502.0
893                               Gone with the Wind  7.600393       995.0
39821                                            부산행  7.599333       984.0
212                                   Before Sunrise  7.599333       984.0
40015                       Kubo and the Two Strings  7.599138       982.0
1185                                     Raging Bull  7.597751       968.0
27866                 Me and Earl and the Dying Girl  7.597145       962.0
33420                                          Human  7.592638        98.0
17821                            جدایی نادر از سیمین  7.591814       474.0
23399                               The Normal Heart  7.591650       320.0
18252                          The Dark Knight Rises  7.589360      9263.0
2906                                     The General  7.589346       240.0
1233                              Young Frankenstein  7.588076       880.0
24902                               Relatos salvajes  7.587834       878.0
30051                                    The Martian  7.586774      7442.0
42170                                          Logan  7.584420      6310.0
6232                                    Finding Nemo  7.584376      6292.0
25534                   Kingsman: The Secret Service  7.583806      6069.0
23053            Captain America: The Winter Soldier  7.583293      5881.0
36600                      Hunt for the Wilderpeople  7.583122       453.0
6833                      La passion de Jeanne d'Arc  7.582346       159.0
23465                               Edge of Tomorrow  7.580296      4979.0
475                                    Jurassic Park  7.580206      4956.0
24482                                     Ex Machina  7.579827      4862.0
26566                 Guardians of the Galaxy Vol. 2  7.579811      4858.0
3080                                        Papillon  7.579617       445.0
5016                                 Smultronstället  7.579523       306.0
15348                                    Toy Story 3  7.579183      4710.0
22059            The Hobbit: The Desolation of Smaug  7.578841      4633.0

[250 rows x 3 columns]